### ISSUE TITLE
Attempting to create or edit a macro fails when SuperSource boolean commands are present

### ISSUE THREAD

**Issue by Lange** [LibAtem/AtemMacroEditor#2]
![image](https://user-images.githubusercontent.com/873012/43551595-2bd68ea6-95ad-11e8-810c-f7e91107bf7f.png)

This seems to happen regardless of which slot is chosen to save the macro to. The slots I am attempting to save to do not currently have macros in them.

**Comment by Lange** [comment]
This seems to also happen when attempting to save edits to an existing macro.

**Comment by Lange** [comment]
It looks like the issue is specific to some SuperSource commands.

**Comment by Lange** [comment]
The issue is specific to SuperSource boolean commands. This is the full list of commands which have this problem:

1. `SuperSourceBoxMaskEnable`
2. `SuperSourceBoxEnable`
3. `SuperSourceBorderEnable`
4. `SuperSourceArtAbove`

**Comment by Julusian** [comment]
That was an easy fix. Should be working now https://drive.google.com/file/d/1KMS9F8xBbnWB_Pm5IpV7PK_7R6440jC3/view?usp=sharing

**Comment by Lange** [comment]
Yep, all good now!

**Comment by Lange** [comment]
Spoke too soon, seeing this error now:
```
System.InvalidOperationException: There is an error in XML document (3, 36). ---> System.InvalidOperationException: Instance validation error: 'false' is not a valid value for AtemBool.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMacro.Read2_AtemBool(String s)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMacro.Read19_MacroOperation(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMacro.Read20_Macro(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMacro.Read21_Macro()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at AtemMacroEditor.Controllers.MacrosController.<Post>d__4.MoveNext() in C:\Code\AtemMacroEditor\AtemMacroEditor\Controllers\MacrosController.cs:line 59
```

**Comment by Julusian** [comment]
Looks like I missed the default case, so it would only save if the input switch was used
https://drive.google.com/file/d/1zGxneGD-HSeulJC5QCH8XsijpBdpgTCp/view?usp=sharing

**Comment by Lange** [comment]
All good now 👌
