### ISSUE TITLE
Moving audio faders causes errors to be printed

### ISSUE THREAD

**Issue by Lange** [LibAtem/AtemMacroEditor#5]
This doesn't affect the usability of the application as far as I can tell, but figured I should report it anyway:

```
2018-08-03 11:58:49,938 [LibAtem.Handle] ERROR LibAtem.Commands.Audio.AudioMixerInputGetCommand - LibAtem.Serialization.SerializationException: AudioMixerInputGetCommand: Auto deserialize length mismatch
   at LibAtem.Serialization.AutoSerializeBase.Deserialize(ParsedByteArray cmd) in C:\code\AtemMacroEditor\LibAtem\LibAtem\Serialization\AutoSerializeBase.cs:line 136
   at LibAtem.Commands.CommandParser.Parse(ParsedCommand rawCmd) in C:\code\AtemMacroEditor\LibAtem\LibAtem\Commands\CommandParser.cs:line 22
```

EDIT: It does not happen when moving the Master or Monitor faders. It does happen when moving any other fader.

**Comment by Julusian** [comment]
Which firmware version? I'm not getting this on 7.2
I remember reading there are significant audio changes in 7.4 which would explain this. 
But this wont have any effect on this project

**Comment by Lange** [comment]
I am indeed on 7.4.

**Comment by Julusian** [comment]
This is a bug in the main library, so I am moving it there https://github.com/LibAtem/LibAtem/issues/1
